In [2]:
import numpy as np
M = np.array([[2, 1, 0], [0, 4, 0], [0, 0, 5]])
print("M:")
v = np.array([1.5, 2, 3])
print("v:")


M:
v:


In [19]:
print(M @ v)  # Matrix-vector multiplication
print((M @ v).shape)  # Matrix-vector multiplication
# ones = np.ones((3,))
ones = np.ones(3)
print(ones @ M @ v)
print(M @ ones)
print(ones @ M)

[ 5.  8. 15.]
(3,)
28.0
[3. 4. 5.]
[2. 5. 5.]


In [20]:
print(v)
print(np.asarray(v, dtype=float).ravel())


[1.5 2.  3. ]
[1.5 2.  3. ]


In [8]:
print(np.outer(v, ones))

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [16]:
print(10*(M @ v))
print(float(np.dot(ones, M @ v)))
print(10 / float(np.dot(ones, M @ v)))

[ 40  80 150]
27.0
0.37037037037037035


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# A has shape (3, 3)
# A.T has shape (3, 3) too — but we’ll dot with a column of ones
ones = np.ones((A.shape[0], 1))  # column vector (3, 1)

col_sum = ones.T @ A  # shape (1, 3)
print(col_sum.ravel())


<built-in method ravel of numpy.ndarray object at 0x112ce4390>


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.sum(A, axis=0))  # sum over rows for each column
# print(np.sum(A, axis=1))  # sum over columns for each row

[12 15 18]
[ 6 15 24]


In [9]:
n = 2
N = n + 1
t = [1, 2, 3, 4, 5, 6]
print(t[0:N-1])
print(t[N-1:2*N-2])
print(t[2*N-2:3*N-3])


[1, 2]
[3, 4]
[5, 6]


In [3]:
import numpy as np
print(np.any(np.array([-1, 1]) > 0))

True


In [9]:
import numpy as np
import random as random
guesses = []
n = 2
N = n + 1
attempt_total_num = 20
for alpha in [i / attempt_total_num for i in range(1,attempt_total_num)]:
    # print(np.concatenate([np.array([alpha]), np.array([1-alpha]), np.zeros(3*N-5)]))
    print(np.concatenate([np.array([random.random()]), np.zeros(3*N-4)]))

    # guesses.append(np.concatenate([np.array([alpha]), np.array([1-alpha]), np.zeros(3*N-1)]))    # attempt_t

[0.31495779 0.         0.         0.         0.         0.        ]
[0.32782852 0.         0.         0.         0.         0.        ]
[0.20406009 0.         0.         0.         0.         0.        ]
[0.46845302 0.         0.         0.         0.         0.        ]
[0.1005946 0.        0.        0.        0.        0.       ]
[0.17223223 0.         0.         0.         0.         0.        ]
[0.65237234 0.         0.         0.         0.         0.        ]
[0.95466318 0.         0.         0.         0.         0.        ]
[0.08229314 0.         0.         0.         0.         0.        ]
[0.33429023 0.         0.         0.         0.         0.        ]
[0.44619995 0.         0.         0.         0.         0.        ]
[0.98166922 0.         0.         0.         0.         0.        ]
[0.76377672 0.         0.         0.         0.         0.        ]
[0.67366273 0.         0.         0.         0.         0.        ]
[0.07815568 0.         0.         0.         0.       

In [11]:
n = 4
N = n + 1
import numpy as np
from scipy.stats import reciprocal
x = reciprocal(a=1e-2, b=1e2).rvs(size=N - 1)
print(x)

print(np.diag(reciprocal(a=1e-2, b=1e2).rvs(size=N-1), k = 1))
print(np.diag(reciprocal(a=1e-2, b=1e2).rvs(size=N-1), k = -1))

[ 0.91463654  5.29261809 15.53176618  5.44618984]
[[ 0.         79.93040367  0.          0.          0.        ]
 [ 0.          0.          6.35234024  0.          0.        ]
 [ 0.          0.          0.          0.2077074   0.        ]
 [ 0.          0.          0.          0.          0.15669726]
 [ 0.          0.          0.          0.          0.        ]]
[[ 0.          0.          0.          0.          0.        ]
 [ 1.90888848  0.          0.          0.          0.        ]
 [ 0.         51.77023919  0.          0.          0.        ]
 [ 0.          0.          0.23978074  0.          0.        ]
 [ 0.          0.          0.          0.07409012  0.        ]]


In [12]:
print(np.floor((n + 2) / 2).astype(int))

3


In [ ]:
print(np.concatenate([np.array([1]), np.zeros(3*N-4)]))

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
