In [18]:
import numpy as np
M = np.array([[2, 1, 0], [0, 4, 0], [0, 0, 5]])
print("M:")
v = np.array([1.5, 2, 3])
print("v:")


M:
v:


In [19]:
print(M @ v)  # Matrix-vector multiplication
print((M @ v).shape)  # Matrix-vector multiplication
# ones = np.ones((3,))
ones = np.ones(3)
print(ones @ M @ v)
print(M @ ones)
print(ones @ M)

[ 5.  8. 15.]
(3,)
28.0
[3. 4. 5.]
[2. 5. 5.]


In [20]:
print(v)
print(np.asarray(v, dtype=float).ravel())


[1.5 2.  3. ]
[1.5 2.  3. ]


In [8]:
print(np.outer(v, ones))

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [16]:
print(10*(M @ v))
print(float(np.dot(ones, M @ v)))
print(10 / float(np.dot(ones, M @ v)))

[ 40  80 150]
27.0
0.37037037037037035


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# A has shape (3, 3)
# A.T has shape (3, 3) too — but we’ll dot with a column of ones
ones = np.ones((A.shape[0], 1))  # column vector (3, 1)

col_sum = ones.T @ A  # shape (1, 3)
print(col_sum.ravel())


<built-in method ravel of numpy.ndarray object at 0x112ce4390>
